config/routes.rb
Rails.application.routes.draw do
  resources :investors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/investor.rb
class Investor < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :dob, presence: true
  validates :phone_number, presence: true
  validates :street_address, presence: true
  validates :state, presence: true
  validates :zip_code, presence: true

  has_one_attached :photo_identification
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/investors_controller.rb
class InvestorsController < ApplicationController
  before_action :set_investor, only: %i[ show edit update destroy ]

  # GET /investors or /investors.json
  def index
    @investors = Investor.all
  end

  # GET /investors/1 or /investors/1.json
  def show
  end

  # GET /investors/new
  def new
    @investor = Investor.new
  end

  # GET /investors/1/edit
  def edit
  end

  # POST /investors or /investors.json
  def create
    @investor = Investor.new(investor_params)

    respond_to do |format|
      if @investor.save
        format.html { redirect_to investor_url(@investor), notice: "Investor was successfully created." }
        format.json { render :show, status: :created, location: @investor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @investor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /investors/1 or /investors/1.json
  def update
    respond_to do |format|
      if @investor.update(investor_params)
        format.html { redirect_to investor_url(@investor), notice: "Investor was successfully updated." }
        format.json { render :show, status: :ok, location: @investor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @investor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investors/1 or /investors/1.json
  def destroy
    @investor.destroy

    respond_to do |format|
      format.html { redirect_to investors_url, notice: "Investor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_investor
      @investor = Investor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def investor_params
      params.require(:investor).permit(:first_name, :last_name, :dob, :phone_number, :street_address, :state, :zip_code, :photo_identification)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/investors_helper.rb
module InvestorsHelper
end

app/views/investors/_form.html.erb
<%= form_with(model: investor) do |form| %>
  <% if investor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(investor.errors.count, "error") %> prohibited this investor from being saved:</h2>

      <ul>
        <% investor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :dob, style: "display: block" %>
    <%= form.date_field :dob %>
  </div>

  <div>
    <%= form.label :phone_number, style: "display: block" %>
    <%= form.text_field :phone_number %>
  </div>

  <div>
    <%= form.label :street_address, style: "display: block" %>
    <%= form.text_field :street_address %>
  </div>

  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.text_field :state %>
  </div>

  <div>
    <%= form.label :zip_code, style: "display: block" %>
    <%= form.text_field :zip_code %>
  </div>

  <div>
    <%= form.label :photo_identification, style: "display: block" %>
    <%= form.file_field :photo_identification %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/investors/_investor.html.erb
<div id="<%= dom_id investor %>">
  <p>
    <strong>First name:</strong>
    <%= investor.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= investor.last_name %>
  </p>

  <p>
    <strong>Dob:</strong>
    <%= investor.dob %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= investor.phone_number %>
  </p>

  <p>
    <strong>Street address:</strong>
    <%= investor.street_address %>
  </p>

  <p>
    <strong>State:</strong>
    <%= investor.state %>
  </p>

  <p>
    <strong>Zip code:</strong>
    <%= investor.zip_code %>
  </p>

  <p>
    <strong>Photo identification:</strong>
    <%= link_to investor.photo_identification.filename, investor.photo_identification if investor.photo_identification.attached? %>
  </p>

</div>

app/views/investors/edit.html.erb
<h1>Editing investor</h1>

<%= render "form", investor: @investor %>

<br>

<div>
  <%= link_to "Show this investor", @investor %> |
  <%= link_to "Back to investors", investors_path %>
</div>

app/views/investors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Investors</h1>

<div id="investors">
  <% @investors.each do |investor| %>
    <%= render investor %>
    <p>
      <%= link_to "Show this investor", investor %>
    </p>
  <% end %>
</div>

<%= link_to "New investor", new_investor_path %>

app/views/investors/new.html.erb
<h1>New investor</h1>

<%= render "form", investor: @investor %>

<br>

<div>
  <%= link_to "Back to investors", investors_path %>
</div>

app/views/investors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @investor %>

<div>
  <%= link_to "Edit this investor", edit_investor_path(@investor) %> |
  <%= link_to "Back to investors", investors_path %>

  <%= button_to "Destroy this investor", @investor, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParallelMarkets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>